[package]
name = "discord_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
websocket = "0.27.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
rand = "0.8.5"
dotenvy = "0.15.7"